# App Name
spring.application.name=CollegeStudentPortal

# Database Details
spring.datasource.url=jdbc:mysql://localhost:3306/collegestudentportal
spring.datasource.username=root
spring.datasource.password=NikhilKute
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
